### ISSUE TITLE
use dockerize to check if database is online before starting kopano-server

### ISSUE THREAD

**Issue by fbartels** [guitarmarx/kopano-image#2]
Hi, one more thing.

In https://github.com/guitarmarx/kopano-image/blob/ebc19cfacf067488d916afc5b25320669698fe47/entrypoint.sh#L144-L155 you are looping until kopano-server has started (as per your comment to wait for the database). This could be simplified by using [dockerize](https://github.com/jwilder/dockerize). See https://github.com/fbartels/kopano-docker/blob/compose/core/start-service.sh#L43-L48 for an example.

(additionally you many want to start the other kopano services only after kopano-server has started)

**Comment by guitarmarx** [comment]
Hi, thank you for your improvements and the link to zokradonh/kopano-docker :) I will integrate dockerize in the next commits
